### ISSUE TITLE
SPM installation

### ISSUE THREAD

**Issue by jtouzy** [jatoben/CommandLine#102] opened 2017-06-11 05:02 UTC
Hi, 

Your module cannot be installed with SPM :

```swift
import PackageDescription

let package = Package(
    name: "MyProject",
    targets: [],
    dependencies: [
        .Package(url: "https://github.com/jatoben/CommandLine.git",
                 majorVersion: 2)
    ]
)
```

**swift package fetch**
```
Fetching https://github.com/jatoben/CommandLine.git
Cloning https://github.com/jatoben/CommandLine.git
Resolving https://github.com/jatoben/CommandLine.git at 2.2.0
error: the directory Tests/CommandLine has an invalid name ('CommandLine'): the name of a test module has no 'Tests' suffix
fix: rename the directory 'Tests/CommandLine' to have a 'Tests' suffix
```

**Comment by matejkosiarcik** [comment] 2017-07-15 13:29
This is duplicate of: [#98](https://github.com/jatoben/CommandLine/issues/98)

**Comment by jatoben** [comment] 2018-12-28 23:40
This repository is being archived. See https://github.com/jatoben/CommandLine/issues/111.

**Closed by jatoben** 2018-12-28 23:40 UTC
